# YAML configuration for Me computation. Copy this file, rename it as 'config.yaml' and
# edit parameters.
# IMPORTANT: Type sensitive information (e.g. passwords) only in files named 'config.yaml'
# (they are ignored by git)

download:
  # The database URL for s2s (can be also on a remote machine), will replace
  # the corresponding parameter in the download config
  dburl: 'postgresql://me:<password>@localhost/me_06_2020'

# The destination directory for the computed tabular (HDF, CSV) and report (HTML) files:
destidir: '/home/me/medb/me_computed'
