# YAML configuration to be used in the Me computation. If you add new items, consider
# editing :func:`_check_config` in `mecompute.py` to check parameters before running the script

# Download configs (absolute path) to be used (one config per download)
# The database URL will be fetched from the first file (it should be always the same in any case)
DOWNLOAD_CONFIGS:
  - /home/me/medb/download/download.eida.yaml
  - /home/me/medb/download/download.iris.yaml

# processing config (absolute path) to be used in the PROCESSING_MODULE below
PROCESSING_CONFIG: /home/me/medb/processing/me_compute.yaml

# processing module (absolute path) to process new downloaded data:
PROCESSING_MODULE: /home/me/medb/processing/me_compute.py

# output directory (absolute path)
OUTPUT_DIRECTORY: /home/me/medb/me_computed