# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Python application on latest Ubuntu

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mecompute/**'
      - 'test/**'
      - 'setup.py'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mecompute/**'
      - 'test/**'
      - 'setup.py'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -e ".[dev]"
    - name: Test with pytest
      run: |
        pytest -xvvv ./test
